
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author zorin99
 */
public class LoginForm extends javax.swing.JFrame {
    MainForm mainform;
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
    }
    public LoginForm(MainForm mform){
        this();
        mainform = mform;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CloseButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UserNameField = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        DivisionCombo = new javax.swing.JComboBox<>();
        PasswordField = new javax.swing.JPasswordField();
        BkgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(590, 398));
        setMinimumSize(new java.awt.Dimension(590, 398));
        setPreferredSize(new java.awt.Dimension(590, 398));
        setResizable(false);
        getContentPane().setLayout(null);

        CloseButton.setForeground(new java.awt.Color(204, 12, 7));
        CloseButton.setText("Close");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CloseButton);
        CloseButton.setBounds(240, 270, 88, 28);

        jLabel1.setFont(new java.awt.Font("Ume Gothic S5", 0, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("   GM-System");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 10, 200, 37);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 12, 7));
        jLabel2.setText("User Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 130, 79, 18);

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 12, 7));
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(12, 176, 79, 18);

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 12, 7));
        jLabel4.setText("Division:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(12, 222, 79, 18);
        getContentPane().add(UserNameField);
        UserNameField.setBounds(103, 125, 210, 28);

        LoginButton.setForeground(new java.awt.Color(204, 12, 7));
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButton);
        LoginButton.setBounds(130, 270, 95, 28);

        DivisionCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin" }));
        getContentPane().add(DivisionCombo);
        DivisionCombo.setBounds(103, 217, 210, 28);
        getContentPane().add(PasswordField);
        PasswordField.setBounds(100, 170, 210, 28);

        BkgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_fitness2.jpg"))); // NOI18N
        getContentPane().add(BkgroundLabel);
        BkgroundLabel.setBounds(0, 0, 590, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        /* 
        username: magico
        password: magico
        */
        
        try{
            String username = UserNameField.getText();
            char[] password = PasswordField.getPassword();
            String pass = String.valueOf(password);
            
            if(!"magico".equals(username) || !"magico".equals(pass))
                    throw new Exception("Invalid Login..");
           
            MainForm mainform = new MainForm(this);
            mainform.setVisible(true);
            this.setVisible(false);
             
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());       
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BkgroundLabel;
    private javax.swing.JButton CloseButton;
    private javax.swing.JComboBox<String> DivisionCombo;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
